[project]
name = "llama-index-readers-gemini"
version = "0.1.0"
description = "llama-index readers gemini integration"
authors = [
    {name = "sumitaryal",email = "sumitaryal310@hotmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pdf2image (>=1.17.0,<2.0.0)",
    "google-genai (>=1.4.0,<2.0.0)",
    "llama-index (>=0.12.22,<0.13.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
